### ISSUE TITLE
Oauth does not work

### ISSUE THREAD

**Issue by PVince81** [owncloud/files_external_gdrive#1]
WIP

**Comment by Hemant-Mann** [comment]
@PVince81 Should I make a PR for updating the **gdrive.js** based on the changes done in the core [https://github.com/owncloud/core/pull/28179](https://github.com/owncloud/core/pull/28179)

**Comment by PVince81** [comment]
@Hemant-Mann that would be great! I hope it will make it work again.

**Comment by PVince81** [comment]
Fix is here: https://github.com/owncloud/files_external_gdrive/pull/8
