### ISSUE TITLE
compatibility issue

### ISSUE THREAD

**Issue by ghost** [owncloud/files_external_gdrive#19]
i just wanted to install this app to my brand-new Nextcloud server (latest version 13.0.1) and got a warning when running the `occ app:enable` prompt.

>[Exception]
>App "Google Drive external storage support" cannot be installed because it is not compatible with this version of the server.

any chance of getting this sorted out?

**Comment by PVince81** [comment]
this ownCloud app is likely not compatible with Nextcloud
