### ISSUE TITLE
Cannot connect

### ISSUE THREAD

**Issue by PVince81** [owncloud/files_external_gdrive#2]
If oauth tokens were setup before upgrading to this app, the authorization does work.

But there seem to be API differences to the version there was in OC core.
Since here we use composer, it likely pulled a more recent version of the SDK so the code will need adjusting.

That, or find out what version we had before and force composer to use that one.
But I think we should rather focus on the latest version because we'll eventually want all this to work with Guzzle v6 (see https://github.com/owncloud/core/pull/28063)

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/files_external_gdrive/pull/6

**Comment by PVince81** [comment]
looks like a lot of the SDK APIs have changed...that will need a lot of work... unless we decide to revert back to the old SDK version just for now (which also works with the old Guzzle).

Seems a lot will depend on the Guzzle decision

**Comment by Hemant-Mann** [comment]
Yes there are API changes in the SDK because it's in BETA and they change whenever they feel like it.

One of the errors - storage test fails because exception is thrown [https://github.com/owncloud/files_external_gdrive/blob/master/lib/Storage/Google.php#L645](https://github.com/owncloud/files_external_gdrive/blob/master/lib/Storage/Google.php#L645)
by the method `free_space` in `lib/Backend/Google.php` class

Response sent by `/apps/files_external/globalstorages/30?testOnly=true`
```json
{"id":30,"mountPoint":"\/GoogleDrive","backend":"googledrive","authMechanism":"oauth2::oauth2","backendOptions":{"configured":"true","client_id":"client_id","client_secret":"client_secret","token":"{\"access_token\":\"hash\",\"token_type\":\"Bearer\",\"expires_in\":3600,\"refresh_token\":\"some_value\",\"created\":1499226334}"},"priority":100,"mountOptions":{"encrypt":true,"previews":true,"enable_sharing":false,"filesystem_check_changes":1,"encoding_compatibility":false},"status":1,"statusMessage":"Google_Service_Exception: {\n \"error\": {\n  \"errors\": [\n   {\n    \"domain\": \"global\",\n    \"reason\": \"required\",\n    \"message\": \"The 'fields' parameter is required for this method.\",\n    \"locationType\": \"parameter\",\n    \"location\": \"fields\"\n   }\n  ],\n  \"code\": 400,\n  \"message\": \"The 'fields' parameter is required for this method.\"\n }\n}\n","userProvided":false,"type":"system"}
```

**Comment by Hemant-Mann** [comment]
@PVince81 @DeepDiver1975 There is a flysystem adapter for Google Drive [https://github.com/nao-pon/flysystem-google-drive](https://github.com/nao-pon/flysystem-google-drive)
Why not use that instead of dealing with the API changes in the SDK. Thoughts?

**Comment by PVince81** [comment]
@Hemant-Mann that could be a good idea, yes. My original concern was that it would take a while to do the port but then if it anyway would take a lot of time to port to the new SDK, then the move to flysystem could be worthwhile, assuming that the adapter is being maintained.

I think a few months/years ago when we looked at flysystem there was no GDrive adapter yet.

@Hemant-Mann as someone who ported Dropbox to the flysystem adapter, how much time do you think it would take to do the same for the GDrive implementation ? Note that GDrive has a few twists like allowing multiple files with the same name to exist within the same folder... and Google Docs must use an export API to be downloaded... so likely more work than for Dropbox.

**Comment by PVince81** [comment]
let's continue the flysystem discussion here: https://github.com/owncloud/files_external_gdrive/issues/7

**Comment by PVince81** [comment]
Fix is here: https://github.com/owncloud/files_external_gdrive/pull/8
