### ISSUE TITLE
problem with smb share

### ISSUE THREAD

**Issue by adam-wolak** [owncloud/files_external_gdrive#25]
I have strange problems with external smb (cifs) storage.
I mounted it with user/password - Sometimes works sometimes not
Error while getting file info: {"Exception":"Icewind\\SMB\\Exception\\TimedOutException","Message":"\/","Code":110,"Trace":"#0 \/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/NativeState.php(49): Icewind\\SMB\\Exception\\Exception::fromMap(Array, 110, '\/')\n#1 \/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/NativeState.php(61): Icewind\\SMB\\NativeState->handleError('\/')\n#2 \/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/NativeState.php(170): Icewind\\SMB\\NativeState->testResult(false, 'smb:\/\/192.168.1...')\n#3 \/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/NativeShare.php(107): Icewind\\SMB\\NativeState->stat('smb:\/\/192.168.1...')\n#4 \/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/NativeShare.php(103): Icewind\\SMB\\NativeShare->getStat('\/')\n#5 \/var\/www\/nextcloud\/apps\/files_external\/lib\/Lib\/Storage\/SMB.php(141): Icewind\\SMB\\NativeShare->stat('\/')\n#6 \/var\/www\/nextcloud\/apps\/files_external\/lib\/Lib\/Storage\/SMB.php(241): OCA\\Files_External\\Lib\\Storage\\SMB->getFileInfo('\/')\n#7 \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Common.php(449): OCA\\Files_External\\Lib\\Storage\\SMB->stat('')\n#8 \/var\/www\/nextcloud\/apps\/files_external\/lib\/Lib\/Storage\/SMB.php(555): OC\\Files\\Storage\\Common->test()\n#9 \/var\/www\/nextcloud\/apps\/files_external\/lib\/config.php(234): OCA\\Files_External\\Lib\\Storage\\SMB->test(false, true)\n#10 \/var\/www\/nextcloud\/apps\/files_external\/lib\/Controller\/StoragesController.php(256): OC_Mount_Config::getBackendStatus('\\\\OCA\\\\Files_Exte...', Array, false, true)\n#11 \/var\/www\/nextcloud\/apps\/files_external\/lib\/Controller\/StoragesController.php(305): OCA\\Files_External\\Controller\\StoragesController->updateStorageStatus(Object(OCA\\Files_External\\Lib\\StorageConfig), true)\n#12 [internal function]: OCA\\Files_External\\Controller\\StoragesController->show(7, true)\n#13 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(161): call_user_func_array(Array, Array)\n#14 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(91): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Files_External\\Controller\\GlobalStoragesController), 'show')\n#15 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/App.php(115): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Files_External\\Controller\\GlobalStoragesController), 'show')\n#16 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(47): OC\\AppFramework\\App::main('OCA\\\\Files_Exter...', 'show', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#17 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#18 \/var\/www\/nextcloud\/lib\/private\/Route\/Router.php(297): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#19 \/var\/www\/nextcloud\/lib\/base.php(999): OC\\Route\\Router->match('\/apps\/files_ext...')\n#20 \/var\/www\/nextcloud\/index.php(42): OC::handleRequest()\n#21 {main}","File":"\/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/Exception\/Exception.php","Line":30}

**Comment by PVince81** [comment]
@adam-wolak this is the repository for **ownCloud** and its **Google Drive** integration.

It appears that your problem is related to **nextCloud** and **SMB**, please raise again in the appropriate repository
