### ISSUE TITLE
No response on Grant access button

### ISSUE THREAD

**Issue by markus-hsk** [owncloud/files_external_gdrive#28]
On the try to connect Google Drive, the "Grant Access" button does not open the Response page. The Error console is showing this message:

> HTTP 422 Unprocessable Entity
> "{"message":"Unbefriedigende Authentifizierungsmechanismus Parameter"}"

![owncloud_gdrive_error](https://user-images.githubusercontent.com/13730463/54588194-8e677880-4a22-11e9-9cb2-8e75fcbaff42.jpg)

Used Owncloud Version 10.1.0.4

**Comment by chris922** [comment]
Same here, if you need any information please let me know. I was not able to find anything regarding this request in the OC logs (logging is set in UI to "all")

ownCloud version 10.0.8.5

Request URL https://MYOWNCLOUD/apps/files_external/userstorages
```json
{
	"mountPoint": "GoogleDrive",
	"backend": "googledrive",
	"authMechanism": "oauth2::oauth2",
	"backendOptions": {
		"configured": "",
		"client_id": "CLIENTID",
		"client_secret": "CLIENTSECRET",
		"token": ""
	},
	"testOnly": true,
	"mountOptions": {
		"encrypt": true,
		"previews": true,
		"enable_sharing": false,
		"filesystem_check_changes": 1,
		"encoding_compatibility": false
	}
}
```

**Comment by karakayasemi** [comment]
Hi, we have an open pull request that may solve this issue in core repo: https://github.com/owncloud/core/pull/34987. If you would like to help, you can apply the patch and share result. Thanks.

**Comment by markus-hsk** [comment]
Hi @karakayasemi, thank you! I'll give it a try, but you'll have to be patient, because at the moment i've no time for this. I will come back, then i have time to check it!

**Comment by markus-hsk** [comment]
Hi @karakayasemi, thank you! I'll give it a try, but you'll have to be patient, because at the moment i've no time for this. I will come back, then i have time to check it!

**Comment by markus-hsk** [comment]
Hi @karakayasemi, thank you! I'll give it a try, but you'll have to be patient, because at the moment i've no time for this. I will come back, then i have time to check it!
