### ISSUE TITLE
Grant Access not opening the consent page when mounting as personal mount

### ISSUE THREAD

**Issue by mmattel** [owncloud/files_external_gdrive#30]
Using owncloud 10.1.1 stable on Ubuntu 18.04, mariadb, php7.2, nginx
Browser: Opera, Chrome, Edge on W10x64, no Pop-Up blockers.

I followed the GD preperation on docs https://doc.owncloud.com/server/10.1/admin_manual/configuration/files/external_storage/google.html
(btw, needs an update as screens have changed a bit)

When adding the mount as admin mount it works as expected.
But adding the mount as personal mount has issues.

Entering Client ID and Secret, the mount access button turns as described and expected to red.
Clicking on Grant Access does nothing, exept that the button turns grey. No pop up with the consent page opens. I tried with three different browsers, all the same. Deleting Client ID and/or Secret does not reset the Grant Access button so it can be clicked again. You have to delete the mount and restart.
I monitored the owncloud log and the nginx logs but they show nothing related.

I tested a couple of times both admin and personal mount with different browsers but same results.

I have a working Dropbox personal mount...

It would be great if that gets fixed before 10.2 is out.

@PVince81 @DeepDiver1975

**Comment by karakayasemi** [comment]
@mmattel I believe this problem solved via #29. If you would like to test it, you can use stable10 core branch. Since this app seperated from core master, also you can test on core master branch by installing this app. Thanks.

**Comment by mmattel** [comment]
I have tested with stable10.
The consent page opens when trying to mount as personal mount 😄.

**Comment by mmattel** [comment]
Closing, fixed by #29
