### ISSUE TITLE
Cannot save config, unprocessable entity

### ISSUE THREAD

**Issue by PVince81** [owncloud/files_external_gdrive#5]
When trying to setup GDrive from scratch as global storage, the network returns with 422 Unprocessable Entity with the message "Unsatisfied authentication mechanism parameters".

**Comment by PVince81** [comment]
Not sure if anything changed with the flow @Hemant-Mann ?

From what I see when trying to save the config the value of "configured" is empty, but isn't optional, so the AuthMechanism fails validation.

Clicking "Grant Access" doesn't do anything because it first tries to save the config, which fails.

@Hemant-Mann any idea ?

**Comment by PVince81** [comment]
seems `gdrive.js` wasn't loaded, now I'm a step further. debugging oauth2.php now

**Comment by PVince81** [comment]
hmm the token is stored as the string `[Object object]`

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/files_external_gdrive/pull/6

**Comment by Hemant-Mann** [comment]
>When trying to setup GDrive from scratch as global storage, the network returns with 422 Unprocessable Entity with the message "Unsatisfied authentication mechanism parameters".

Yes I also got the same problem but since the save config request was fired before clicking on the **Grant Access** button I thought it was some bug in owncloud not my code. And then I was redirected for authentication and final config was saved so I didnot give it much thought
